name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        env:
          CI: true
          NODE_ENV: "test"

      - name: Run Tests
        run: npm run coverage
        env:
          NODE_ENV: "test"
          CI: true

      - name: Check coverage
        run: npm run check-coverage
        env:
          NODE_ENV: "test"
          CI: true
