on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if package version changed
        id: check_version
        run: |
          version="v$(cat package.json | jq -r '.version')"
          if [ $(git tag -l "$version") ]; then
            echo "Tag $version already exists."
          else
            echo "version_tag=$version" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        if: steps.check_version.outputs.version_tag
        run: |
          gh release create ${{ steps.check_version.outputs.version_tag }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
